# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  #vmImage: ubuntu-latest
  name: selfhosted

steps:
- script: |
    echo "=== listing files ==="
    ls -lR
  displayName: 'display files'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: mvn clean install -B
  displayName: 'Run Raw Maven Command'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/target'   # Path to the folder or file you want to upload
    artifactName: 'mbrooks-app-1.0-SNAPSHOT.jar'     # Name of the artifact 
    publishLocation: 'pipeline'           # Stores the artifact in Azure Pipelines